### PR TITLE
Switch to nose-py3

### PR DESCRIPTION
**Pull request by ian659**

### CODE REVIEW

**Comment by aliwinter** [comment]
@ian659 
use pytest instead of nose-py3 since pytest is fully supported with newer versions of python, and all test seem to pass with using pytest. just make sure to replace everywhere it uses nosetests with pytest.

below is the results for running `pytest`
```
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================== 38 passed, 10 warnings in 9.47s =====================================
```

when running the original `nosetests` we get 38 tests as well
```

......................................
----------------------------------------------------------------------
Ran 38 tests in 10.290s

OK
```

**Comment by aliwinter** [comment]
on an additional note if we want to use pytest with coverage to replace nosetests --with-coverage install `pytest-cov` module as well then run `python -m pytest --cov --cov-config=.coveragerc`

**Review by aliwinter — CHANGES_REQUESTED** [review]
use `pytest` instead of nose-py3 since pytest is fully supported with newer versions of python, and all test seem to pass with using pytest. just make sure to replace everywhere it uses nosetests with pytest.

below is the results for running pytest

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================== 38 passed, 10 warnings in 9.47s =====================================

when running the original nosetests we get 38 tests as well


......................................
----------------------------------------------------------------------
Ran 38 tests in 10.290s

OK

on an additional note if we want to use pytest with coverage to replace `nosetests --with-coverage` add the `pytest-cov` module to the requirements-dev.txt as well then replace anywhere you see the `nosetests --with-coverage` with `python -m pytest --cov --cov-config=.coveragerc`

**Comment by ian659** [comment]
Withdrawing in favour of https://github.com/winterlightlabs/bucket-antivirus-function/pull/27

**Pull request closed without merging**
